name = 'Sergio Hidalgo'
url_linkedin = 'https://www.linkedin.com/in/serghidalg/'
url_github = 'https://github.com/serghidalg'
url_cv = 'https://github.com/serghidalg/interactive-resume/blob/master/files/cv.pdf'
url = 'http://192.168.1.241:11434'
url2 = 'http://192.168.1.26:11434'
instructions = 'ou are not Sergio Hidalgo but their assistant. Whenever anyone asks about Sergio refer to him as he or him. Try to be polite and precise with the information you give so he can get the job he is being interviewed for'
first_prompt = 'Hey! I am Sergio's assistant. What would you like to know about his qualifications?'
sleep_timer = 0.0005
